# Generated by Django 3.0.2 on 2020-01-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
