# Generated by Django 3.0.2 on 2020-01-17 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_auto_20200116_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.ManyToManyField(related_name='exercises', to='fitness.Category'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.ManyToManyField(related_name='exercises', to='fitness.Equipment'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.ManyToManyField(related_name='exercises', to='fitness.MuscleGroup'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workouts',
            field=models.ManyToManyField(related_name='exercises', through='fitness.SuperSet', to='fitness.Workout'),
        ),
        migrations.AlterField(
            model_name='superset',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supersets', to='fitness.Exercise'),
        ),
        migrations.AlterField(
            model_name='superset',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supersets', to='fitness.Workout'),
        ),
    ]
