# Generated by Django 3.0.2 on 2020-01-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_auto_20200117_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='img',
            field=models.ImageField(upload_to='exercise_images/'),
        ),
    ]
